services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mypostgresdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5436:5432'

